Parameters:
    KeyPair:
        Type: String
Resources:
    MyCluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: "MyCluster"
    MySecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: "This is a security group"
            SecurityGroupIngress:
                -
                    CidrIp: "0.0.0.0/0"
                    IpProtocol: "tcp"
                    FromPort: 22
                    ToPort: 22
    MyEC2ECSRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Principal:
                            Service: "ec2.amazonaws.com"
                        Action:
                            - "sts:AssumeRole"
            Policies:
                -
                    PolicyName: "EC2AllowECS"
                    PolicyDocument:
                        Version: "2012-10-17"
                        Statement:
                            -
                                Effect: "Allow"
                                Action:
                                    - "ec2:DescribeTags"
                                    - "ecs:CreateCluster"
                                    - "ecs:DeregisterContainerInstance"
                                    - "ecs:DiscoverPollEndpoint"
                                    - "ecs:Poll"
                                    - "ecs:RegisterContainerInstance"
                                    - "ecs:StartTelemetrySession"
                                    - "ecs:UpdateContainerInstancesState"
                                    - "ecs:Submit*"
                                    - "ecr:GetAuthorizationToken"
                                    - "ecr:BatchCheckLayerAvailability"
                                    - "ecr:GetDownloadUrlForLayer"
                                    - "ecr:BatchGetImage"
                                    - "logs:CreateLogStream"
                                    - "logs:PutLogEvents"
                                Resource: "*"

    EC2ECSInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        DependsOn: MyEC2ECSRole
        Properties:
            InstanceProfileName: "ECSForEC2"
            Roles:
                - !Ref MyEC2ECSRole
    MyLaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        DependsOn:
            - MySecurityGroup
            - MyCluster
            - EC2ECSInstanceProfile
        Properties:
            LaunchTemplateData:
                KeyName: !Ref KeyPair
                InstanceType: "t2.micro"
                ImageId: "ami-0f81924348bcd01a1"
                IamInstanceProfile:
                    Name: !Ref EC2ECSInstanceProfile
                SecurityGroupIds:
                    - !GetAtt MySecurityGroup.GroupId
                UserData:
                    Fn::Base64:
                        !Sub |
                            #!/bin/bash -xe
                            echo "ECS_CLUSTER=${MyCluster}" >> /etc/ecs/ecs.config
    MyAutoScalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        DependsOn: MyLaunchTemplate
        Properties:
            LaunchTemplate:
                LaunchTemplateId: !Ref MyLaunchTemplate
                Version: 1
            AvailabilityZones:
                - "us-east-1a"
                - "us-east-1b"
            MinSize: 2
            MaxSize: 2
    MyTaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            ContainerDefinitions:
                -
                    Image: "redis"
                    Name: "redis"
                    Memory: 512
    MyService:
        Type: AWS::ECS::Service
        DependsOn:
            - MyCluster
            - MyTaskDefinition
            - MyAutoScalingGroup
        Properties:
            Cluster: !Ref MyCluster
            SchedulingStrategy: "REPLICA"
            DesiredCount: 1
            TaskDefinition: !Ref MyTaskDefinition
            LaunchType: "EC2"
