Parameters:
    ClusterStack:
        Type: String
    RedisLogsGroup:
        Type: String
        Default: "my-redis-logs-group"
Resources:
    MyRedisLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Ref RedisLogsGroup
    MyTaskDefinition:
        Type: AWS::ECS::TaskDefinition
        DependsOn: MyRedisLogGroup
        Properties:
            ContainerDefinitions:
                -
                    Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/redis:latest"
                    Name: "redis"
                    Memory: 512
                    LogConfiguration:
                        LogDriver: "awslogs"
                        Options:
                            awslogs-group: !Ref RedisLogsGroup
                            awslogs-region: "us-east-1"
                    PortMappings:
                        -
                            ContainerPort: 6379
                            HostPort: 6379
    MyService:
        Type: AWS::ECS::Service
        DependsOn: MyTaskDefinition
        Properties:
            Cluster:
                Fn::ImportValue:
                    !Sub "${ClusterStack}-ClusterId"
            SchedulingStrategy: "REPLICA"
            DesiredCount: 1
            TaskDefinition: !Ref MyTaskDefinition
            LaunchType: "EC2"
