Parameters:
    KeyPair:
        Type: String
    AvZone:
        Type: String
    OwnerId:
        Type: Number
    SourceId:
        Type: String
    SourceRegion:
        Type: String
    InstanceId:
        Type: String
    DBPort:
        Type: Number
        Default: 3306
Resources:
    MyEC2SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: "This is a security group"
            SecurityGroupIngress:
                -
                    CidrIp: "0.0.0.0/0"
                    IpProtocol: "tcp"
                    FromPort: 22
                    ToPort: 22
                -
                    CidrIp: "0.0.0.0/0"
                    IpProtocol: "tcp"
                    FromPort: !Ref DBPort
                    ToPort: !Ref DBPort
    MyDbSecurityGroup:
        Type: AWS::RDS::DBSecurityGroup
        DependsOn: MyEC2SecurityGroup
        Properties:
            GroupDescription: "This is a db security group"
            DBSecurityGroupIngress:
                -
                    EC2SecurityGroupId: !GetAtt MyEC2SecurityGroup.GroupId
                    EC2SecurityGroupOwnerId: !Ref OwnerId
    MyMysqlDBReadReplica:
        Type: AWS::RDS::DBInstance
        DependsOn:
            - MyEC2SecurityGroup
            - MyDbSecurityGroup
        Properties:
            AvailabilityZone: !Ref AvZone
            Engine: "mysql"
            EngineVersion: "8.0.16"
            DBInstanceClass: "db.t2.micro"
            DBInstanceIdentifier: !Ref InstanceId
            AllocatedStorage: "20"
            PubliclyAccessible: false
            SourceDBInstanceIdentifier: !Ref SourceId
            SourceRegion: !Ref SourceRegion
            Port: !Ref DBPort
            DBSecurityGroups:
                - !Ref MyDbSecurityGroup
    MyEC2:
        Type: AWS::EC2::Instance
        DependsOn:
            - MyEC2SecurityGroup
            - MyMysqlDBReadReplica
        Properties:
            KeyName: !Ref KeyPair
            InstanceType: "t2.micro"
            ImageId: "ami-00dc79254d0461090"
            AvailabilityZone: !Ref AvZone
            SecurityGroupIds:
                - !GetAtt MyEC2SecurityGroup.GroupId
            UserData:
                Fn::Base64:
                    !Sub |
                        #!/bin/bash -xe
                        echo "${MyMysqlDBReadReplica.Endpoint.Address}" > /mysql-replica-addr.txt
                        echo "${MyMysqlDBReadReplica.Endpoint.Port}" > /mysql-replica-port.txt
                        yum update -y
                        yum install mysql -y
