Parameters:
    DeploymentBucketName:
        Type: String
Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref DeploymentBucketName
            Tags:
                - Key: Name
                  Value: !Ref DeploymentBucketName
